version: '3'
services:
  scipy-ml-notebook:
    build:
      context: ./images/scipy-ml-notebook
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
