namespace: test-server

deployment:
  gpu:
    replicaCount: 1
    name: gpu-tester
    image: jdkindley/test-server:1.0
    port: 50051
    volume:
      jobtemplate:
        name: job-template
        path: /etc/gpu-tester/
      app:
        name: grpc
        path: /app

service:
  gpu:
    name: gpu-tester-service
    port: 50051
    targetPort: 50051
    protocol: TCP
    
vs:
  name: tester-server
  host: superqa.ucsd.edu
  secret: tls-secret
  upstream:
    gpu:
      name: gpu-tester
      service: gpu-tester-service
      port: 50051
      path: /gpu_tester.Test/Test

saccount:
  name: internal-kubectl

rolebinding:
  name: modify-pods-to-sa
  
configmap:
  name: config
  jobtemplate: job-template.yaml
  server: server.py
  pb2grpc: gpu_tester_pb2_grpc.py
  pb2: gpu_tester_pb2.py

role:
  name: job-role
  groups: ["batch",""]
  resources: ["jobs","pods","pods/log"]
  verbs: ["create", "get", "list", "delete"]

tls:
  type: kubernetes.io/tls
  name: tls-secret
  crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUd3ekNDQmF1Z0F3SUJBZ0lRUTRiSlZJZFVFVFVNUDFlUWc1WmVpVEFOQmdrcWhraUc5dzBCQVFzRkFEQjIKTVFzd0NRWURWUVFHRXdKVlV6RUxNQWtHQTFVRUNCTUNUVWt4RWpBUUJnTlZCQWNUQ1VGdWJpQkJjbUp2Y2pFUwpNQkFHQTFVRUNoTUpTVzUwWlhKdVpYUXlNUkV3RHdZRFZRUUxFd2hKYmtOdmJXMXZiakVmTUIwR0ExVUVBeE1XClNXNURiMjF0YjI0Z1VsTkJJRk5sY25abGNpQkRRVEFlRncweU1URXlNakl3TURBd01EQmFGdzB5TWpFeU1qSXkKTXpVNU5UbGFNSG94Q3pBSkJnTlZCQVlUQWxWVE1STXdFUVlEVlFRSUV3cERZV3hwWm05eWJtbGhNU3d3S2dZRApWUVFLRXlOVmJtbDJaWEp6YVhSNUlHOW1JRU5oYkdsbWIzSnVhV0VzSUZOaGJpQkVhV1ZuYnpFTk1Bc0dBMVVFCkN4TUVWVU5UUkRFWk1CY0dBMVVFQXhNUWMzVndaWEp4WVM1MVkzTmtMbVZrZFRDQ0FTSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU1wUmNvRXB0QWl3VE15UFlYMzkzK25yTk5qSjNVbWI2bUV2V0RWNwpXbHBqYmhpdTZ5ZWdrUmNJTC94cFFadlRpSHExZUNzSXV6Sko0ejZrbFpmU094Z2lzalM5OVFJRXZTMDE1ZE5NCldYcHBsRElkdmh5Sm1YRGJLWktFODlJWHFLRm5iQkVZcjFIWUsxN2czMkdWK05KS2VUbmF4K2J0c1MwQm9BUzIKTFQzK1BZU3YrWU4vL0dIend5NlZWVkN3dEtDTlhheGNEUjdzdXJkK21Dajk2Rnp4QTdMaXc3THdOd2hzM3ZqbApscVNUK2t2RDVrRDMzdXVZb0xhYytOalVOcExObTlTVXE1RDUwWmRacWF2c0FwSDVWcDB6L0RMaEZXZ1lDckYrCkg4VUs2YWhpdnlaK1ZOd3FsN0JTQzU4NllMdUVvODVFeHhwQTk5OU4zZzNMTm5FQ0F3RUFBYU9DQTBjd2dnTkQKTUI4R0ExVWRJd1FZTUJhQUZCNEZvM2VQYkpiaVc0ZExwclNHckhFQURPYzRNQjBHQTFVZERnUVdCQlFmT1hqeApTakUyYTFYVjMxSW04YnFJOWVqMlpUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0RBWURWUjBUQVFIL0JBSXdBREFkCkJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdad1lEVlIwZ0JHQXdYakJTQmd3ckJnRUUKQWE0akFRUURBUUV3UWpCQUJnZ3JCZ0VGQlFjQ0FSWTBhSFIwY0hNNkx5OTNkM2N1YVc1amIyMXRiMjR1YjNKbgpMMk5sY25RdmNtVndiM05wZEc5eWVTOWpjSE5mYzNOc0xuQmtaakFJQmdabmdRd0JBZ0l3UkFZRFZSMGZCRDB3Ck96QTVvRGVnTllZemFIUjBjRG92TDJOeWJDNXBibU52YlcxdmJpMXljMkV1YjNKbkwwbHVRMjl0Ylc5dVVsTkIKVTJWeWRtVnlRMEV1WTNKc01IVUdDQ3NHQVFVRkJ3RUJCR2t3WnpBK0JnZ3JCZ0VGQlFjd0FvWXlhSFIwY0RvdgpMMk55ZEM1MWMyVnlkSEoxYzNRdVkyOXRMMGx1UTI5dGJXOXVVbE5CVTJWeWRtVnlRMEZmTWk1amNuUXdKUVlJCkt3WUJCUVVITUFHR0dXaDBkSEE2THk5dlkzTndMblZ6WlhKMGNuVnpkQzVqYjIwd0d3WURWUjBSQkJRd0VvSVEKYzNWd1pYSnhZUzUxWTNOa0xtVmtkVENDQVg4R0Npc0dBUVFCMW5rQ0JBSUVnZ0Z2QklJQmF3RnBBSGNBUnFWVgo2M1g2a1NBd3RhS0phZlR6ZlJFc1FYUysvVW00aGF2eS9IRCtiVWNBQUFGOTVDSGVKZ0FBQkFNQVNEQkdBaUVBCm9JK0FBTC9XWUdXZ1djd3hLQi8zMm50cDVuUSsrcnR0Smg0SXo3azljaXdDSVFDVDA2c3Rad1doVUljNER2elAKWFZBYVVseWNPOU1maCtxU0VqdDEwTkpmN2dCMUFFSEl5ckhmSWtaS0VNYWhPZ2xDaDE1T01Zc2JBK3ZyUzhkbwo4SkJpbGdiMkFBQUJmZVFoM2U0QUFBUURBRVl3UkFJZ1Z4eitYUDgzTW1jdTJVTExCa1dveWpCb0ZrOTRyTHhvCk90RjUwb2RmMmlnQ0lHNnJReWdRSTdFdG91WDQ1NDNFOGIxVkhrdTA0VUlNWmxFUkRvRm5FQTlFQUhjQUtYbSsKOEo0NU9TSHdWbk9mWTZWMzViNVhmWnhnQ3ZqNVRWMG1YQ1ZkeDRRQUFBRjk1Q0hkeFFBQUJBTUFTREJHQWlFQQpwNlNIYzgrV2VBZHlWVlg0OVpmUTlHTmJMWGdtcGNnQm51dm1wRnBzR25zQ0lRQzAwRVp0OW56NDllTEl1L0hBCkhFOFBYUlZBdlZpQjNQOHV3Z2dYQ3kxa1N6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFkWEZGN0xCSC9mSXQKYnBPaVlsR2hiNjczVW5Kb2lic0RXbGpKb050THp0NEN3N2Q0dmtzK0NMcjkvZzNmMFpoZlRIWTZnTmh3NkFGUQpSS3hHcUlqSk5CdHRVL3Nub0d1Q0pxNEdNTXg2aWlJVS9QdTVzMTc2OWdkRlVySUZoT3hNWGhSSWZ2MGkwK1RDClc0NnEvZmpQZmRtc2hpT0JJQWsxenJQUWRXQnBnQnI2enc3THdZVVZEK2pLZVBVeWF2NmFHMDlIRXJzc2Ntb1kKZG9XclFvaWdjVGFGRlhBS2xXQ3h6VDJZWWxyUUVvaWd1Q0g3YzloaUhUUllCMEFkNHlTYXFZcUhRMVV2QUhiWgo2ZlNHamdoNndUci9PQkV4Q0l2NGNCM2NmTHZ4aUxmbnNEeXkwWHl0STYyWjBtVSt5N1UzWk1VN2o1MjlHOWNOCkNOMlluUldPR0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRREtVWEtCS2JRSXNFek0KajJGOS9kL3A2elRZeWQxSm0rcGhMMWcxZTFwYVkyNFlydXNub0pFWENDLzhhVUdiMDRoNnRYZ3JDTHN5U2VNKwpwSldYMGpzWUlySTB2ZlVDQkwwdE5lWFRURmw2YVpReUhiNGNpWmx3MnltU2hQUFNGNmloWjJ3UkdLOVIyQ3RlCjROOWhsZmpTU25rNTJzZm03YkV0QWFBRXRpMDkvajJFci9tRGYveGg4OE11bFZWUXNMU2dqVjJzWEEwZTdMcTMKZnBnby9laGM4UU95NHNPeThEY0liTjc0NVpha2svcEx3K1pBOTk3cm1LQzJuUGpZMURhU3padlVsS3VRK2RHWApXYW1yN0FLUitWYWRNL3d5NFJWb0dBcXhmaC9GQ3Vtb1lyOG1mbFRjS3Bld1VndWZPbUM3aEtQT1JNY2FRUGZmClRkNE55elp4QWdNQkFBRUNnZ0VBSTZpdFZPU2p6YkE5S1FUUWV5Tm05dFMwOE16TGl2REhJNi96alNHYnNEaTgKSysrUWxPQnhFaTBvUUFYUlFZVE1Ga3lyekhIeWhJK1BWUGd2UVo0Vk9sRExOZzZSQTNVUVhzcVVJbVRmbEhyTgpXdlB4RVJpVGlkZW5BU01iMGxqSEtRT1FnWWJuUjdhaEZrenVNa1g3b0J6dU51cy90bzBJWUZWYi9kaWFLc1czCkp5Wm5vZklFZXpLQkV4SWdGV1ZLRDJBcWNOVEtVUC9DOWEvZWd4UkNTMGpyUEZaRkdOTnRYSEVMaEhLQW5oVTcKc3NEeGs1Q2h4SFJBa0duYmpBTjVqSUlIU0ZtTjBZNUgrQlVPWkQvZlhxQ1Y3VGljVnJsZUhjV013NDBDeWpDMApwOU9yQmd5TGRLZUZSK3RHcXF3cktKbC9uUVY1WFdHVGhpM3ZmMDkwM1FLQmdRRDlCaTdXaitEL2Y2UzJJZGFDCm92bGZKTXJiamJjTHdRSEg4K2FhMS9tQXRHZitWdm13NzR3NnRRTGIyekpua0ZmYWhqT0VFSmRnV2ZLdmVOQU4KVkNpM2Y0ZzZZVVJ1NFErbW44V1hJUmt6alAvVmVFM0JqbHpoUGYrZmZiWWx1TkY5MVR5VlRKSW5UYms2a3phMQpJUFhJNFlCMkZLanZMODk1Y0wwNVM1VE1kd0tCZ1FETXNwaW41YkJENDE5M3FVWjZDZkxVa2pTYTlzcUYrR09sCmlpYnZDMytOMnNYcGhHUHBMeUlvbkEzV3dmMmdaOUF5ZWl6QlkxNVFxeGNsL3VwMnJoR3lvRFpXUC8wT29ZRy8KanlYVFF1Wm9xVnNCNzJpN2JBZlBDSklmc1M2YXA5RWE5c0hXTjBmcmZEOTBmRWhocEdRb0MrbHlJU0RWSUdOcwpPRHY5Vy9TV1Z3S0JnR2I5Z1Vzc3ZYVENUQlVtcU4zNzRHMXQySFNOdHBnK002OWtBOVc3VzMrYjcwaUR0cGJpCnFyMnF1RU10Y2RMZDJpVEV3MnRhSllPK21SMzdteFFSMFpEL2hEL2ZINi9TUkVDYWdCOElCZTRKMG9qZHN5aTUKL2V4aEJBK3paOVRxNmJyQ2RTcUFSRzFqSWFaS0RkYWtWK2N3Z3MyTmswWG92QmErWVFkVlVIZjVBb0dBTE8xRgo5QlBGakNEcll5Z1QvOVVQSnZpdjh4TVhnQy8wTHZFVGVvUGJpeGJwT1VlRlpqaWlGcWVwb2VrUjhaTFhienpCCmRmQ0pVc3M2V1d5SnFXS3JIN2xxTTZQM3RxNWIrOTgvUGc4QTR4ZklrYlFxR0hpdGZoTXpmeUUwU1YxcjE2OHcKL0FOR0Ziay9kQ0dUQVZ0RFlFYTlCZitmWlNlbXFxbnRBTDZlQUNFQ2dZRUFpK2cwc3RqcEN2dVVCKzV0RkZzZwpKNUp5OE1IeHB5VkJaS3dzZWpjUHJkREdTZWI3V010RUI0b0NrbmpzanhKdXlsZkRrUDhjMUhMWllYb2pFMTlnCmRYK2FidlBCRGlQdEFuV3NTWUc5Vm9JVDJuQkVpY2h0ajY4bmxHbDh6YVFsUXl6SXgzaWp4UE92MmFMRkVjaFAKcUpzam9ZVEJTZEFabFNZVkExaW5wMjg9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K

  