apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.gpu.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "test-server-chart.deployment.gpu-tester.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.gpu.replicaCount }}
  selector:
    matchLabels:
      {{- include "test-server-chart.deployment.gpu-tester.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "test-server-chart.deployment.gpu-tester.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.saccount.name }} 
      containers:
      - name: {{ .Values.deployment.gpu.name }}
        image: {{ .Values.deployment.gpu.image }}
        ports:
        - containerPort: {{ .Values.deployment.gpu.port }}
        volumeMounts:
        - mountPath: {{ .Values.deployment.gpu.volume.app.path}}
          name: {{ .Values.deployment.gpu.volume.app.name }}
        - mountPath: {{ .Values.deployment.gpu.volume.jobtemplate.path}}
          name: {{ .Values.deployment.gpu.volume.jobtemplate.name}}
      volumes:
      - name: {{ .Values.deployment.gpu.volume.app.name }}
        configMap:
        # adds files to /app
          name: {{ .Values.configmap.name}}
          items:
          - key: {{ .Values.configmap.server}}
            path: {{ .Values.configmap.server}}
          - key: {{ .Values.configmap.pb2grpc }}
            path: {{ .Values.configmap.pb2grpc}}
          - key: {{ .Values.configmap.pb2 }}
            path: {{ .Values.configmap.pb2 }}
      - name: {{ .Values.deployment.gpu.volume.jobtemplate.name}}
      # adds files to /etc/gpu-tester/
        configMap:
          name: {{ .Values.configmap.name}}
          items:
          - key: {{ .Values.configmap.jobtemplate}}
            path: {{ .Values.configmap.jobtemplate}}
