# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gpu_tester.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gpu_tester.proto',
  package='gpu_tester',
  syntax='proto3',
  serialized_options=b'\n\033io.grpc.examples.gpu_testerB\016GpuTesterProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10gpu_tester.proto\x12\ngpu_tester\"2\n\x10GpuTesterRequest\x12\r\n\x05image\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"%\n\x0eGpuTesterReply\x12\x13\n\x0btest_output\x18\x01 \x01(\t2W\n\tGpuTester\x12J\n\x0cLaunchGpuJob\x12\x1c.gpu_tester.GpuTesterRequest\x1a\x1a.gpu_tester.GpuTesterReply\"\x00\x42\x35\n\x1bio.grpc.examples.gpu_testerB\x0eGpuTesterProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_GPUTESTERREQUEST = _descriptor.Descriptor(
  name='GpuTesterRequest',
  full_name='gpu_tester.GpuTesterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='gpu_tester.GpuTesterRequest.image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='gpu_tester.GpuTesterRequest.command', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=82,
)


_GPUTESTERREPLY = _descriptor.Descriptor(
  name='GpuTesterReply',
  full_name='gpu_tester.GpuTesterReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='test_output', full_name='gpu_tester.GpuTesterReply.test_output', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['GpuTesterRequest'] = _GPUTESTERREQUEST
DESCRIPTOR.message_types_by_name['GpuTesterReply'] = _GPUTESTERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GpuTesterRequest = _reflection.GeneratedProtocolMessageType('GpuTesterRequest', (_message.Message,), {
  'DESCRIPTOR' : _GPUTESTERREQUEST,
  '__module__' : 'gpu_tester_pb2'
  # @@protoc_insertion_point(class_scope:gpu_tester.GpuTesterRequest)
  })
_sym_db.RegisterMessage(GpuTesterRequest)

GpuTesterReply = _reflection.GeneratedProtocolMessageType('GpuTesterReply', (_message.Message,), {
  'DESCRIPTOR' : _GPUTESTERREPLY,
  '__module__' : 'gpu_tester_pb2'
  # @@protoc_insertion_point(class_scope:gpu_tester.GpuTesterReply)
  })
_sym_db.RegisterMessage(GpuTesterReply)


DESCRIPTOR._options = None

_GPUTESTER = _descriptor.ServiceDescriptor(
  name='GpuTester',
  full_name='gpu_tester.GpuTester',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=123,
  serialized_end=210,
  methods=[
  _descriptor.MethodDescriptor(
    name='LaunchGpuJob',
    full_name='gpu_tester.GpuTester.LaunchGpuJob',
    index=0,
    containing_service=None,
    input_type=_GPUTESTERREQUEST,
    output_type=_GPUTESTERREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GPUTESTER)

DESCRIPTOR.services_by_name['GpuTester'] = _GPUTESTER

# @@protoc_insertion_point(module_scope)
