apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.name }}
  namespace: {{ .Values.namespace }}
data:
  tls.crt: {{ .Values.tls.crt }}
  tls.key: {{ .Values.tls.key }}
type: {{ .Values.tls.type }}