apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }} 
  name: {{ .Values.service.gpu.name }}
spec:
  selector:
    {{- include "test-server-chart.service.gpu-tester.labels" . | nindent 6 }}
  ports:
  - protocol: {{ .Values.service.gpu.protocol }}
    port: {{ .Values.service.gpu.port }}
    targetPort: {{ .Values.service.gpu.targetPort }}
    