name: LOCAL Build and Test

env:
  DOCKER_CLIENT_TIMEOUT: "300"
  COMPOSE_HTTP_TIMEOUT: "300"

on:
  push:
    paths:
      - "images/**"
      - "model/**"
      - "scripts/**"
      - "dodo.py"
      - ".github/workflows/local-build-test.yml"

  pull_request:
    branches: [ main ]
    paths:
      - "images/**"
      - "model/**"
      - "scripts/**"
      - "dodo.py"
      - ".github/workflows/local-build-test.yml"

  workflow_dispatch:

jobs:
  docker-pipeline:
    name: Docker Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pip dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install -r scripts/requirements.txt

      - name: Run Build and Tests
        run: |
          source venv/bin/activate
          python3 scripts/main.py

      - name: Check Free Space
        run: |
          echo "Free space:"
          df -h