name: Build parent

on:
  push:

jobs:
  build-parent-notebook:
    uses: ucsd-ets/datahub-docker-stack/.github/workflows/build.yml@david-experimental
    with:
      dockerfile: images/datahub-base-notebook/Dockerfile
