name: Build parent

on:
  push:

jobs:
  build-parent-notebook:
    uses: ucsd-ets/datahub-docker-stack/.github/workflows/build.yml@david-experimental
    with:
      context: images/datahub-base-notebook

  build-datascience:
    needs: build-parent-notebook
    uses: ucsd-ets/datahub-docker-stack/.github/workflows/build.yml@david-experimental
    with:
      context: images/datascience

  build-scipy-ml:
    needs: build-parent-notebook
    uses: ucsd-ets/datahub-docker-stack/.github/workflows/build.yml@david-experimental
    with:
      context: images/scipy-ml-notebook

  build-rstudio:
    needs: build-parent-notebook
    uses: ucsd-ets/datahub-docker-stack/.github/workflows/build.yml@david-experimental
    with:
      context: images/rstudio-notebook
