name: Build parent

on:
  push:

jobs:
  build-parent-notebook:
    uses: ucsd-ets/datahub-docker-stack/.github/workflows/build.yml@david-experimental
    with:
      context: images/datahub-base-notebook
      tag: python-3.9.5

  build-datascience:
    needs: build-parent-notebook
    uses: ucsd-ets/datahub-docker-stack/.github/workflows/build.yml@david-experimental
    with:
      context: images/datascience-notebook
      tag: 2023.1-stable

  build-scipy-ml:
    needs: build-parent-notebook
    uses: ucsd-ets/datahub-docker-stack/.github/workflows/build.yml@david-experimental
    with:
      context: images/scipy-ml-notebook
      tag: 2023.1-stable

  build-rstudio:
    needs: build-parent-notebook
    uses: ucsd-ets/datahub-docker-stack/.github/workflows/build.yml@david-experimental
    with:
      context: images/rstudio-notebook
      tag: 2023.1-stable
